Lesson4
ilyalychkou/javafordev pull request #2
Opened 2020-08-11 23:45 UTC by ilyalychkou

Lesson 4 tasks 1-3

2020-08-15 21:02 UTC, AntonShtabnoy commented on src/com/javafordev/lesson4/task1/Airline.java
> +    private String dayOfWeek;
В задании написано днИ недели - а у тебя обычное поле String, как буду туда записывать дни?

2020-08-15 21:04 UTC, AntonShtabnoy commented on src/com/javafordev/lesson4/task1/Airline.java
> +            this.destination = " ";
Данные проверки лучше вынести в отдельный класс Validator - тогда их можно переиспользовать например в setter

2020-08-15 21:08 UTC, AntonShtabnoy commented on src/com/javafordev/lesson4/task1/Airline.java
> +    public static void printAirlinesByDestination(Airline[] airlines, String destination) {
Данные методы лучше вынести в отдельный класс - AirlineService, обычно делают класс - модель, и отдельный класс для работы с группами таких объектов. Также возможно в этом классе сделать поле массив Airlines и с ним работать в методах

2020-08-15 21:13 UTC, AntonShtabnoy commented on src/com/javafordev/lesson4/task1/Airline.java
> +    public static void printAirlinesByDestination(Airline[] airlines, String destination) {
Также лучше сделать метод find которые будет возвращать список - это гибче, так как я с этим списком могу потом что-нить еще сделать, в том числе и вывести на экран

2020-08-15 21:15 UTC, AntonShtabnoy commented on src/com/javafordev/lesson4/task1/Airline.java
> +        }
Все хорошо, почитай что-то такое forEach и как это переписать можно

2020-08-15 21:17 UTC, AntonShtabnoy commented on src/com/javafordev/lesson4/task1/Airline.java
> +    }
Аналогично комментарию выше

2020-08-15 21:21 UTC, AntonShtabnoy commented on src/com/javafordev/lesson4/task1/Airline.java
> +public class Airline {
В классе типа модель - должны быть getter и setter

2020-08-16 10:28 UTC, ilyalychkou commented on src/com/javafordev/lesson4/task1/Airline.java
> +    private String dayOfWeek;
добавил в класс Airline public static поле - массив строк с днями недели, static - тк это поле класса, конкретному объекту оно не нужно, значения меняться и сеттится по-разному для разных объектов не будут, public - тк данные массиве общедоступны, не содержат внутренней логики класса. для такие полей возможно тип enum даже лучше подойдет чем массив

2020-08-17 20:37 UTC, ilyalychkou commented on src/com/javafordev/lesson4/task1/Airline.java
> +    public static void printAirlinesByDestination(Airline[] airlines, String destination) {
вынес методы для фильтрации массива объектов в класс AirlineService

2020-08-17 20:45 UTC, ilyalychkou commented on src/com/javafordev/lesson4/task1/Airline.java
> +    }
переписал на foreach

2020-08-17 20:46 UTC, ilyalychkou commented on src/com/javafordev/lesson4/task1/Airline.java
> +public class Airline {
добавил getters и setters, реализовал обращение к полям через них а не напрямую

2020-08-17 20:46 UTC, ilyalychkou commented on src/com/javafordev/lesson4/task1/Airline.java
> +        }
переписал на foreach

2020-08-17 21:23 UTC, ilyalychkou commented on src/com/javafordev/lesson4/task1/Airline.java
> +            this.destination = " ";
вынес в отдельный класс Validator, использовал в конструкторе и сеттерах

2020-08-23 22:30 UTC, ilyalychkou commented on src/com/javafordev/lesson4/task1/Airline.java
> +    private String dayOfWeek;
передаю в конструктор и сеттер массив daysOfWeek с переменным количеством параметром типа String

2020-08-23 22:30 UTC, ilyalychkou commented on src/com/javafordev/lesson4/task1/Validator.java
> +                    + "Допустимые значения - латиница, не пустая строка");
пока убрал вывод про латиницу, подумаю как делать для нее валидацию

2020-08-23 22:31 UTC, ilyalychkou commented on src/com/javafordev/lesson4/task1/Validator.java
> +        for (Object element : arrayName) {
исправил на Airline

2020-08-23 22:32 UTC, ilyalychkou commented on src/com/javafordev/lesson4/task1/AirlineService.java
> +    public Airline[] findAirlinesByFilter(Airline[] airlines, String filterName, String filterValue) {
передаю в методы поиска поле ailrlines объекта AirlineService

2020-08-23 22:33 UTC, ilyalychkou commented on src/com/javafordev/lesson4/task2/Fraction.java
> +        }
убрал для массива с четным количеством элементов

2020-08-23 22:34 UTC, ilyalychkou commented on src/com/javafordev/lesson4/task3/Triangle.java
> +    }
добавил проверку триугольника на корректность в сеттеры, те при изменении стороны

2020-08-23 22:34 UTC, ilyalychkou commented on src/com/javafordev/lesson4/task3/Triangle.java
> +        }
добавил else if

2020-08-23 22:35 UTC, ilyalychkou commented on src/com/javafordev/lesson4/task1/Validator.java
> +                    validatedParameterValue = parameterValue;
исправил

2020-08-23 22:36 UTC, ilyalychkou commented on src/com/javafordev/lesson4/task1/Validator.java
> +                System.out.println("Входнои массив содержит null элементы!");
возвращаю новый массив с длиной = длине arrayName, элементы инициализируются по умолчанию

2020-08-23 22:37 UTC, ilyalychkou commented on src/com/javafordev/lesson4/task2/Fraction.java
> +    }
исправил, в том числе реализацию методов

2020-08-23 22:37 UTC, ilyalychkou commented on src/com/javafordev/lesson4/task3/Triangle.java
> +    }
исправил

2020-08-23 22:38 UTC, ilyalychkou commented on src/com/javafordev/lesson4/task2/Fraction.java
> +    protected double fraction;
удалил fraction

2020-08-23 22:44 UTC, ilyalychkou commented on src/com/javafordev/lesson4/task1/AirlineRunner.java
> +        System.out.println();
вынес в отдельный метод

2020-08-27 06:05 UTC, alka1ra commented on src/com/javafordev/lesson4/task1/AirlineService.java
> +    public Airline[] findAirlinesByFilter(Airline[] airlines, String filterName, String filterValue) {
поскольку метод вызывается на объекте airlineService, внутренним параметром которого и являются airlines, то можно при вызове метода не вызывать getAirlines, a просто получить airlines внутри метода, чтобы в параметрах не было airlines, которые и так находятся внутри airlineService: `findAirlinesByFilter(String filterName, String filterValue)`

2020-08-27 06:20 UTC, alka1ra requested changes

2020-08-27 06:20 UTC, alka1ra commented on src/com/javafordev/lesson4/task1/AirlineRunner.java
> +        printArrayOfAirlines(airlinesFilteredByDayOfWeekAndDepartureTime);
поскольку метод вызывается на объекте airlineService, внутренним параметром которого и являются airlines, то можно при вызове метода не вызывать getAirlines, a просто получить airlines внутри метода, чтобы в параметрах не было airlines, которые и так находятся внутри airlineService: findAirlinesByFilter(String filterName, String filterValue)

2020-08-27 18:10 UTC, ilyalychkou commented on src/com/javafordev/lesson4/task1/AirlineRunner.java
> +        printArrayOfAirlines(airlinesFilteredByDayOfWeekAndDepartureTime);
исправил метод findAirlinesByFilter и findAirlinesByDepatrureTime - удалил избыточный параметр - массив, внутри методов обращение к полю airlines (объект класс AirlineService) через ключевого слово this

2020-08-28 07:57 UTC, alka1ra approved these changes

2020-08-28 07:57 UTC, merged

2020-08-28 17:42 UTC, AntonShtabnoy commented on src/com/javafordev/lesson4/task1/AirlineService.java
> +        }
ты же здесь уже размер нового массива нашел i - и потом нигде не использовал эту переменную

2020-08-28 17:42 UTC, AntonShtabnoy commented on src/com/javafordev/lesson4/task1/Validator.java
> +                System.out.println("Задано некорректное имя входного параметра!");
сделал бы три раздельных валидационных метода

2020-08-28 17:42 UTC, AntonShtabnoy commented on src/com/javafordev/lesson4/task2/Fraction.java
> +    }
вынес бы в аналогичный AirlineService класс

2020-08-28 17:42 UTC, AntonShtabnoy commented on src/com/javafordev/lesson4/task2/Fraction.java
> +            System.out.println(element.toString());
когда в  метод System.out.println передаешь элемент, там автоматически вызывается метод toString

2020-08-28 17:42 UTC, AntonShtabnoy commented on src/com/javafordev/lesson4/task2/Fraction.java
> +    }
Проверки на ноль нет

2020-08-28 17:42 UTC, AntonShtabnoy commented on src/com/javafordev/lesson4/task3/Triangle.java
> +        return Math.sqrt(0.5 * perimeter * (0.5 * perimeter - this.sideOne) * (0.5 * perimeter - this.sideTwo) * (0.5 * perimeter - this.sideThree));
лучше называть calculate - так как get - обычно только с гетерами используется

2020-08-28 17:42 UTC, AntonShtabnoy commented on src/com/javafordev/lesson4/task3/Triangle.java
> +    }
не понятно зачем статические методы, опять же вынес бы в отдельный класс валидатор

2020-08-28 17:42 UTC, AntonShtabnoy commented on src/com/javafordev/lesson4/task3/Triangle.java
> +                }
разделил бы на два метода

2020-08-28 17:42 UTC, AntonShtabnoy commented on src/com/javafordev/lesson4/task3/Triangle.java
> +    }
В класс валидатор

2020-08-28 17:42 UTC, AntonShtabnoy commented on src/com/javafordev/lesson4/task3/Triangle.java
> +    public static double getMinTriangleByFilter(Triangle[] triangles, String filter) {
название лучше find